### ISSUE TITLE
setFlash crash for certain devices 

### ISSUE THREAD

**Issue by davidbilly** [dm77/barcodescanner#116]
Hi @dm77 , 

Can help take on this? Thanks for this great lib!

Caused by: java.lang.RuntimeException: setParameters failed
       at android.hardware.Camera.native_setParameters(Camera.java)
       at android.hardware.Camera.setParameters(Camera.java:1614)
       at me.dm7.barcodescanner.core.BarcodeScannerView.setFlash(BarcodeScannerView.java:118)
       at com.xxx.xxx.activity.onResume(ScanBarcodeActivity2.java:177)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1202)
       at android.app.Activity.performResume(Activity.java:5345)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2816)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2855)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2300)
       at android.app.ActivityThread.access$700(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5279)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by bfg9000d** [comment]
This is a issue with some phones (in my case a xperia running 4.1.2) that dont like having the camera configuration change while autofocusing.

My workaround for that was disabling autofocus and only focusing when the user clicked the screen, and while it was focusing, I disabled the ability to toggle the flash.

You could also try disabling the autofocus temporarily when changing the flash setting, then enabling it again.
