### ISSUE TITLE
Crash on Android M

### ISSUE THREAD

**Issue by lduparc** [dm77/barcodescanner#133]
Test on Android M crash everytime.
UnsatisfiedLinkError : /libiconv.so: has text relocations

How to fix it ?

```
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime: FATAL EXCEPTION: main
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime: Process: com.xxxxx.yyyyy.ppd, PID: 25465
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.xxxxx.yyyyy.ppd.ppd-1/lib/arm/libiconv.so: has text relocations
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:372)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:1076)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at me.dm7.barcodescanner.zbar.ZBarScannerView.<clinit>(ZBarScannerView.java:31)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at com.xxxxx.yyyyy.ppd.workflow.scanner.ScannerFragment.onCreateView(ScannerFragment.java:43)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1026)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1572)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:493)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-07 08:52:52.524 25465-25465/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dm77** [comment]
Please try 1.8.3 version as specified in issue #123

**Comment by PratikPagada** [comment]
Android google nexus 7.1.1 crash everytime.
