### ISSUE TITLE
setOneShotPreviewCallback method of android.hardware.Camera called after the camera is released, which causes exception

### ISSUE THREAD

**Issue by leolovesmile** [dm77/barcodescanner#154]
As you could see, the following exception is found in the android monitor when you run the zxing-sample version 1.8.4.

It could be reproduced by click back button in any activity that has QRcode scan feature.

ZXingScannerView: java.lang.RuntimeException: Method called after release()
     java.lang.RuntimeException: Method called after release()
         at android.hardware.Camera.setHasPreviewCallback(Native Method)
         at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:630)
         at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:153)
         at android.hardware.Camera$EventHandler.handleMessage(Camera.java:840)
         at android.os.Handler.dispatchMessage(Handler.java:99)
         at android.os.Looper.loop(Looper.java:137)
         at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by scic** [comment]
I observe the same error and stacktrace. I'm using the version with zbar 1.8.4 on Android 6 (SDK 23)

````
E/ZBarScannerView: java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                   java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                       at android.hardware.Camera.setHasPreviewCallback(Native Method)
                                       at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:801)
                                       at me.dm7.barcodescanner.zbar.ZBarScannerView.onPreviewFrame(ZBarScannerView.java:134)
                                       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1110)
                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                       at android.os.Looper.loop(Looper.java:148)
                                       at android.os.HandlerThread.run(HandlerThread.java:61)
````

**Comment by yummyChina** [comment]
how to solve this? I met the same question

**Comment by NorbertSzydlowski** [comment]
+1

**Comment by lakshmansai** [comment]
```
    @Override
    public void onBackPressed() {
        mScannerView.stopCamera();           // Stop camera on pause
        super.onBackPressed();
    }
```
this helped me
