### ISSUE TITLE
ArrayIndexOutOfBoundsException in ZBarScannerView.java:86

### ISSUE THREAD

**Issue by akashdeepad** [dm77/barcodescanner#158]
I am getting a random crash after QR code scan has finished. (Not every time)

I am using below version zbar in my gradle file:
me.dm7.barcodescanner:zbar:1.8.3

Below is the crash report found on "Motorola DROID RAZR" running Android version 4.1.2 - 

java.lang.ArrayIndexOutOfBoundsException: length=38016; index=38399
    at me.dm7.barcodescanner.zbar.ZBarScannerView.onPreviewFrame(ZBarScannerView.java:86)
    at android.hardware.Camera$EventHandler.handleMessage(Camera.java:765)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5059)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
    at dalvik.system.NativeStart.main(Native Method)

Please assist me.

**Comment by writtmeyer** [comment]
Same bug here. Happens every now and then. At least on these devices:
- Samsung Galaxy 5, running Android version 5.0
- LG G3, running Android version 5.1.1
