### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by alcntml** [dm77/barcodescanner#187]
My phone is LG g3, OS : 5.0. I use 1.8.4 version of this lib and ı am getting this error and barcode doesn't read. 

Handler (android.hardware.Camera$EventHandler) {ec29f13} sending message to a Handler on a dead thread
                                                                    java.lang.IllegalStateException: Handler (android.hardware.Camera$EventHandler) {ec29f13} sending message to a Handler on a dead thread
                                                                        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                        at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                        at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                        at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                        at android.os.Handler.sendMessage(Handler.java:507)
                                                                        at android.hardware.Camera.postEventFromNative(Camera.java:1344)

**Comment by izBasit** [comment]
Even I get this. It comes and goes many a times. I have to restart my activity to get rid of it.

**Comment by pinetum** [comment]
My phone is Redmin Note 3, OS:6.0(CM13) 
Library version : 1.8.4 version 
I have the same problem.

**Comment by pianetarosso** [comment]
Hi, I've suffered from the same problem. Analyzing the code I found out that I was calling **startCamera** two times, and this brought out issues on thread management in the library.

Try to take a look.

**Comment by Tikso** [comment]
Thankyou pianetarosso . I also had the same problem calling startCamera twice.

**Comment by ahmedeltaher** [comment]
Is there a solution for this bug!
