### ISSUE TITLE
Crash happening on ZXingScannerView.onPreviewFrame 

### ISSUE THREAD

**Issue by santbob** [dm77/barcodescanner#200]
Hi 
Thanks for the library.

We are using `1.8.3` version of the library, upon one successful scan we stop the preview and close the scanner, but sometimes our customers are seeing crash. below is the crash log.

Really appreciate if we can find a fix.

`Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=783360; index=784079
       at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:97)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1573)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5725)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)`

**Comment by MrLyp** [comment]
I have the same problem, it happens every time and I don't know how to fix it.

**Comment by Ekri** [comment]
I have the same problem also.
