### ISSUE TITLE
Scan only QR_CODE

### ISSUE THREAD

**Issue by makiabuan** [dm77/barcodescanner#204]
The app is working now. I have a small problem. I want the app to scan only QR_CODE

i came up with

public void setupFormats() {
     List<BarcodeFormat> formats = new ArrayList<BarcodeFormat>();
     ...
}

I Ctrl+Click the BarcodeFormat and came up with the lists of the formats.

If I want to use only QR_CODE, how can I do it?

Thanks in advance.

**Comment by Jiezhi** [comment]
try this:
```java
List<BarcodeFormat> formats = new ArrayList<>();
        formats.add(BarcodeFormat.QRCODE);
        scannerView.setFormats(formats);
```

**Comment by makiabuan** [comment]
Hi, thank you for your reply. I did what you said. But im being thrown by an error.

E/ZXingScannerView: java.lang.RuntimeException: Method called after release()
                                  java.lang.RuntimeException: Method called after release()
                                    at android.hardware.Camera.setHasPreviewCallback(Native Method)
                                    at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:574)
       at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:153)
                                   at android.hardware.Camera$EventHandler.handleMessage(Camera.java:752)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by chaozaiai** [comment]
@makiabuan I see the error. Hope fix this.
