### ISSUE TITLE
java.lang.RuntimeException: cancelAutoFocus failed in onPause()

### ISSUE THREAD

**Issue by whizzzkey** [dm77/barcodescanner#208]
Hi, got this Issue after upgrading Andoid OS in my ActivityCodeScanner in method onPause():

> @Override
>    public void onPause() {
>      super.onPause();
>      mScannerView.stopCamera();
>    }

Where mScannerView is:

>    @Override
>     public void onCreate(Bundle state) {
>         super.onCreate(state);
>         mScannerView = new ZXingScannerView(this);
>         setContentView(mScannerView);
>         ..............................................
> }

My Device is Huawei Honor 4x (Android 6.0)

StackTrace:
`java.lang.RuntimeException: cancelAutoFocus failed
 at android.hardware.Camera.native_cancelAutoFocus(Native Method)
 at android.hardware.Camera.cancelAutoFocus(Camera.java:1476)
 at me.dm7.barcodescanner.core.CameraPreview.stopCameraPreview(CameraPreview.java:109)
 at me.dm7.barcodescanner.core.BarcodeScannerView.stopCamera(BarcodeScannerView.java:85)
 at com.android.app.mysuperapp.ui.ActivityCodeScanner.onPause(ActivityCodeScanner.java:57)
 at android.app.Activity.performPause(Activity.java:6495)
 at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
 at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3398)
 at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3371)
 at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3346)
 at android.app.ActivityThread.access$1100(ActivityThread.java:165)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:150)
 at android.app.ActivityThread.main(ActivityThread.java:5546)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)`

What other information need to provide?

**Comment by MegaMattMiller** [comment]
Getting something similar:

`java.lang.RuntimeException: cancelAutoFocus failed
                                                                           at android.hardware.Camera.native_cancelAutoFocus(Native Method)
                                                                           at android.hardware.Camera.cancelAutoFocus(Camera.java:1364)
                                                                           at me.dm7.barcodescanner.core.CameraPreview.stopCameraPreview(CameraPreview.java:115)
                                                                           at me.dm7.barcodescanner.core.CameraPreview.surfaceDestroyed(CameraPreview.java:74)
                                                                           at android.view.SurfaceView.updateWindow(SurfaceView.java:696)
                                                                           at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:316)
                                                                           at android.view.View.dispatchDetachedFromWindow(View.java:15847)
                                                                           at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5136)
                                                                           at android.view.ViewGroup.removeAllViews(ViewGroup.java:5082)
                                                                           at me.dm7.barcodescanner.core.BarcodeScannerView.setupLayout(BarcodeScannerView.java:43)
                                                                           at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(BarcodeScannerView.java:87)
                                                                           at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java:31)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:158)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by redbluenat** [comment]
me too, any solutions?

**Comment by JudeRosario** [comment]
Same here .. looks like an old bug is back ! @dm77 .. will really appreciate you taking a look

**Comment by oromis300** [comment]
Just got the same bug. 
I instantiate the view like this.
`scannerView = new ZXingScannerView(this);
            cameraPreview.addView(scannerView);
            scannerView.setAutoFocus(true);
            scannerView.setResultHandler(this); // Register ourselves as a handler for scan results.
            scannerView.startCamera();`

And when i want to stop it 
`scannerView.stopCamera();`

I have a crash

**Comment by amineharbaoui** [comment]
Same Issue here with Nexus 5X (Android version : 8.1.0) 

```
E/CameraPreview: java.lang.RuntimeException: cancelAutoFocus failed
    java.lang.RuntimeException: cancelAutoFocus failed
        at android.hardware.Camera.native_cancelAutoFocus(Native Method)
        at android.hardware.Camera.cancelAutoFocus(Camera.java:1324)
        at me.dm7.barcodescanner.core.CameraPreview.stopCameraPreview(CameraPreview.java:120)
        at me.dm7.barcodescanner.core.BarcodeScannerView.stopCamera(BarcodeScannerView.java:202)
        at ubudu.com.scan_qr.TokenScannerFragment.onPause(TokenScannerFragment.java:102)
        at android.support.v4.app.Fragment.performPause(Fragment.java:2531)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1485)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:3216)
        at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:228)
        at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:447)
        at android.app.Activity.performPause(Activity.java:7153)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
        at android.app.ActivityThread.-wrap15(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by alex-dokienko** [comment]
also got this on 1.9.13

**Comment by yxwandroid** [comment]
Have the same problem
![image](https://user-images.githubusercontent.com/9635493/57189808-a436eb80-6f45-11e9-838b-db2fdda86fae.png)

**Comment by VincentJ1989** [comment]
me too~

**Comment by terryttsai** [comment]
I got the same problem on 1.9.8

**Comment by terryttsai** [comment]
I'm seeing the same error on 1.9.8.

**Comment by rishabhtech1994** [comment]
Please let us know is anyone has solved this issue. I am facing the same issue.
Thank you in advance.

**Comment by bitvale** [comment]
version 1.9.13
No crash, but error persist (Nexus 5X)

![image](https://user-images.githubusercontent.com/14936809/69872053-16de2e80-12bd-11ea-999d-bedca02d9318.png)

**Comment by oznecniV97** [comment]
I have the same problem on an eumlated AVD device.
I found this solution:
```
//solution found on https://stackoverflow.com/a/9127845/6395540
Camera.Parameters p = mCamera.getParameters();
List<String> focusModes = p.getSupportedFocusModes();

if(focusModes != null && focusModes.contains(Camera.Parameters.FOCUS_MODE_AUTO)) {
    //Phone supports autofocus!
}
else {
    //Phone does not support autofocus!
}
```
so I think that where you call the method "setAutoFocus" you need to add the check for autofocus presence.
A good thing can be insert the control inside the public method (public void setAutoFocus(boolean state) in BarcodeScannerView.java) and print log on autofocus failure instead of throwing the exception.
