### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by dante2k** [dm77/barcodescanner#235]
I use dm77 barcodescanner zxing 1.9
Device is SM-G928S, Android version 6.0.1

Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1996)
       at me.dm7.barcodescanner.core.CameraUtils.isFlashSupported(SourceFile:47)
       at me.dm7.barcodescanner.core.BarcodeScannerView.setFlash(SourceFile:153)
       at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(SourceFile:90)
       at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(SourceFile:31)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
#0. Crashed: main: 0 0 0x0000000000000000

```
   at android.hardware.Camera.native_getParameters(Camera.java)
   at android.hardware.Camera.getParameters(Camera.java:1996)
   at me.dm7.barcodescanner.core.CameraUtils.isFlashSupported(SourceFile:47)
   at me.dm7.barcodescanner.core.BarcodeScannerView.setFlash(SourceFile:153)
   at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(SourceFile:90)
   at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(SourceFile:31)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:158)
   at android.app.ActivityThread.main(ActivityThread.java:7237)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by GBenoitG** [comment]
Hi, i'm using ZBar 1.9, with Crashlytics to analyse crashes, we have got the same crash. Here the logs with all threads, perhaps helpful.

[http://pastebin.com/tcr2DjJz](url)

**Comment by kazougagh** [comment]
I am using ZBar 1.9. Crashlytics reports me the same crash.
Thanks.

Same logs as @dante2k

**Comment by spunja** [comment]
Crashlytics has reported the same crash for me as well. Logs are a little different.

Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1996)
       at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:88)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1183)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by semaphore3000** [comment]
I wrote a workaround for the exception thrown:  #305

**Comment by ahmedeltaher** [comment]
@dm77 please we need a solution for this issue.

**Comment by ahmedeltaher** [comment]
this is the fix for this issue: 
problem context: it is happening due to thread race. 
the camera looks released or closed and is null, so we have a null pointer try&catch, in case camera not available don't throw the crash and return false 

https://github.com/dm77/barcodescanner/pull/443
