### ISSUE TITLE
Crashing when applying proguard

### ISSUE THREAD

**Issue by SanyasiraoM** [dm77/barcodescanner#257]
Even I kept below rules,
###ZBarLibrary
-dontwarn me.dm7.barcodescanner.zbar.**
-keep class me.dm7.barcodescanner.zbar.**{*;}
-keep interface me.dm7.barcodescanner.zbar.**{*;}

StackTrack:

FATAL EXCEPTION: main
                                                 Process: com.ibtspl.ibhubsdataentry.alpha, PID: 3451
                                                 java.lang.NoSuchFieldError: no "J" field "peer" in class "Lnet/sourceforge/zbar/ImageScanner;" or its superclasses
                                                     at net.sourceforge.zbar.ImageScanner.init(Native Method)
                                                     at net.sourceforge.zbar.ImageScanner.<clinit>(Unknown Source)
                                                     at me.dm7.barcodescanner.zbar.ZBarScannerView.setupScanner(Unknown Source)
                                                     at me.dm7.barcodescanner.zbar.ZBarScannerView.<init>(Unknown Source)
                                                     at com.ibtspl.ibhubsdata.activity.QRScannerActivity.onCreate(Unknown Source)
                                                     at android.app.Activity.performCreate(Activity.java:6041)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2285)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5276)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by zoonooz** [comment]
Same problem. I added this and it's working now.
```
-keepclassmembers class net.sourceforge.zbar.ImageScanner { *; }
-keepclassmembers class net.sourceforge.zbar.Image { *; }
```

**Comment by SanyasiraoM** [comment]
Thanks :)

**Comment by yq2yizi** [comment]
i have try the way. it's no use.  it's still broken

**Comment by iszhaoqing** [comment]
me too
