### ISSUE TITLE
setPreviewTexture failed

### ISSUE THREAD

**Issue by Carpetfizz** [dm77/barcodescanner#273]
I get the following when my phone enters landscape mode.

This is the block of code it references:

```
    @Override
    public void onPause() {
        super.onPause();
        scannerView.stopCamera();
    }
```

```E/CameraPreview: java.io.IOException: setPreviewTexture failed
                 java.io.IOException: setPreviewTexture failed
                     at android.hardware.Camera.setPreviewSurface(Native Method)
                     at android.hardware.Camera.setPreviewDisplay(Camera.java:629)
                     at me.dm7.barcodescanner.core.CameraPreview.showCameraPreview(CameraPreview.java:83)
                     at me.dm7.barcodescanner.core.CameraPreview.surfaceChanged(CameraPreview.java:68)
                     at android.view.SurfaceView.updateWindow(SurfaceView.java:630)
                     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
                     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                     at android.view.Choreographer.doFrame(Choreographer.java:621)
                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                     at android.os.Handler.handleCallback(Handler.java:751)
                     at android.os.Handler.dispatchMessage(Handler.java:95)
                     at android.os.Looper.loop(Looper.java:154)
                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/CameraPreview: java.io.IOException: setPreviewTexture failed
                 java.io.IOException: setPreviewTexture failed
                     at android.hardware.Camera.setPreviewSurface(Native Method)
                     at android.hardware.Camera.setPreviewDisplay(Camera.java:629)
                     at me.dm7.barcodescanner.core.CameraPreview.showCameraPreview(CameraPreview.java:83)
                     at me.dm7.barcodescanner.core.CameraPreview.surfaceChanged(CameraPreview.java:68)
                     at android.view.SurfaceView.updateWindow(SurfaceView.java:630)
                     at android.view.SurfaceView.setFrame(SurfaceView.java:309)
                     at android.view.View.layout(View.java:17634)
                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                     at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                     at android.view.Choreographer.doFrame(Choreographer.java:621)
                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                     at android.os.Handler.handleCallback(Handler.java:751)
                     at android.os.Handler.dispatchMessage(Handler.java:95)
                     at android.os.Looper.loop(Looper.java:154)
                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/CameraPreview: java.lang.RuntimeException: cancelAutoFocus failed
                 java.lang.RuntimeException: cancelAutoFocus failed
                     at android.hardware.Camera.native_cancelAutoFocus(Native Method)
                     at android.hardware.Camera.cancelAutoFocus(Camera.java:1275)
                     at me.dm7.barcodescanner.core.CameraPreview.stopCameraPreview(CameraPreview.java:115)
                     at me.dm7.barcodescanner.core.BarcodeScannerView.stopCamera(BarcodeScannerView.java:102)
                     at com.example.aramesh.palletscan.ScannerFragment.onPause(ScannerFragment.java:69)
                     at android.app.Fragment.performPause(Fragment.java:2530)
                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1043)
                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
                     at android.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2053)
                     at android.app.FragmentController.dispatchPause(FragmentController.java:209)
                     at android.app.Activity.performPause(Activity.java:6817)
                     at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
                     at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3740)
                     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3717)
                     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3691)
                     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4489)
                     at android.app.ActivityThread.-wrap19(ActivityThread.java)
                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loop(Looper.java:154)
                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/Camera: Error 2
E/CameraPreview: java.io.IOException: setPreviewTexture failed
                 java.io.IOException: setPreviewTexture failed
                     at android.hardware.Camera.setPreviewSurface(Native Method)
                     at android.hardware.Camera.setPreviewDisplay(Camera.java:629)
                     at me.dm7.barcodescanner.core.CameraPreview.showCameraPreview(CameraPreview.java:83)
                     at me.dm7.barcodescanner.core.CameraPreview.surfaceChanged(CameraPreview.java:68)
                     at android.view.SurfaceView.updateWindow(SurfaceView.java:630)
                     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
                     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                     at android.view.Choreographer.doFrame(Choreographer.java:621)
                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                     at android.os.Handler.handleCallback(Handler.java:751)
                     at android.os.Handler.dispatchMessage(Handler.java:95)
                     at android.os.Looper.loop(Looper.java:154)
                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/CameraPreview: java.io.IOException: setPreviewTexture failed
                 java.io.IOException: setPreviewTexture failed
                     at android.hardware.Camera.setPreviewSurface(Native Method)
                     at android.hardware.Camera.setPreviewDisplay(Camera.java:629)
                     at me.dm7.barcodescanner.core.CameraPreview.showCameraPreview(CameraPreview.java:83)
                     at me.dm7.barcodescanner.core.CameraPreview.surfaceChanged(CameraPreview.java:68)
                     at android.view.SurfaceView.updateWindow(SurfaceView.java:630)
                     at android.view.SurfaceView.setFrame(SurfaceView.java:309)
                     at android.view.View.layout(View.java:17634)
                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                     at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                     at android.view.View.layout(View.java:17637)
                     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                     at android.view.Choreographer.doFrame(Choreographer.java:621)
                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                     at android.os.Handler.handleCallback(Handler.java:751)
                     at android.os.Handler.dispatchMessage(Handler.java:95)
                     at android.os.Looper.loop(Looper.java:154)
                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/Camera: Error 2```

**Comment by Eeuro** [comment]
What happens if you leave the app by pushing the "home button" and return back to it? Does your application still work?

**Comment by zhou129311** [comment]
The answer may be helpful to you :) 
https://stackoverflow.com/questions/30616097/android-camera-app-passed-null-surface/30616683#30616683
