### ISSUE TITLE
java.lang.NullPointerException - handleResult

### ISSUE THREAD

**Issue by rusmichal** [dm77/barcodescanner#281]
Hey sometime I got crash below, becuase somehow `scannerView` is null. I dont know why. This is my fragment configuration:

```
protected void onFragmentReady(View view) {       //this is called from onCreateView fragment method
        gson = new Gson();
        isFlashOn = false;
        ViewGroup contentFrame = (ViewGroup) getCurrentActivity().findViewById(R.id.content_frame);
        scannerView = new ZXingScannerView(getCurrentActivity());
        contentFrame.addView(scannerView);
    }

    @Override
    public void handleResult(Result result) {
        scannerView.resumeCameraPreview(ScannerFragment.this);       // NPE!

        try {
            ContactModel userModel = gson.fromJson(result.getText(), ContactModel.class);
            if (userModel != null) {
                ((MainActivity) getCurrentActivity()).hideBottomTabBar();


                getActivity().getSupportFragmentManager().beginTransaction().remove(this).commit();
                getActivity().getSupportFragmentManager().popBackStack();
                getCurrentActivity().showFragment(ScanCardFragment.newInstance(userModel), ScanCardFragment.TAG, true);


            }
        } catch (Exception ex) {
            ((MainActivity) getCurrentActivity()).hideBottomTabBar();
            getActivity().getSupportFragmentManager().beginTransaction().remove(this).commit();
            getActivity().getSupportFragmentManager().popBackStack();
            getCurrentActivity().replaceFragment(OtherScanFragment.newInstance(result.getText()), OtherScanFragment.TAG, true);
        }
    }

    @Override
    public void onResume() {
        super.onResume();
        try {
            scannerView.setResultHandler(this);
            scannerView.startCamera();
            ((MainActivity) getCurrentActivity()).hideBottomTabBar();
        } catch (Exception ex) {
        }
    }

    @Override
    public void onDestroyView() {
        scannerView.stopCamera();
        scannerView.stopCameraPreview();
        scannerView.removeAllViews();
        scannerView = null;
        super.onDestroyView();
    }

```

Error:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void me.dm7.barcodescanner.zxing.ZXingScannerView.resumeCameraPreview(me.dm7.barcodescanner.zxing.ZXingScannerView$ResultHandler)' on a null object reference
       at com.mooduplabs.qrcontacts.fragments.ScannerFragment.handleResult(ScannerFragment.java:62)
       at me.dm7.barcodescanner.zxing.ZXingScannerView$1.run(ZXingScannerView.java:148)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5297)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by mcichecki** [comment]
Hi, did you find any solution?
