### ISSUE TITLE
onPreviewFrame of me.dm7.barcodescanner.zxing.ZXingScannerView > Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by renolooijmans** [dm77/barcodescanner#312]
I keep getting following error while using ZXing barcode scanner. This happens when I press the back button or a custom stop button.

```
E/ZXingScannerView: java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                        java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                            at android.hardware.Camera.setHasPreviewCallback(Native Method)
                                                                            at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:874)
                                                                            at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:171)
                                                                            at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1183)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
```

Please note I already have defined onStop, onPause and onBackPressed in the activity.

```
    protected void onPause() {
        super.onPause();
        scannerView.stopCamera();
    }
```

```
    public void onBackPressed() {
        scannerView.stopCamera();
        super.onBackPressed();
    }
```

```
    protected void onStop() {
        super.onStop();
        scannerView.stopCamera();
    }
```

Am I doing something wrong or is this an issue with the library?

EDIT: I am testing on a Samsung Galaxy S6

**Comment by dm77** [comment]
Hi @renolooijmans. Sorry for not replying sooner. Are you able to replicate the same issue with https://github.com/dm77/barcodescanner/tree/master/zxing-sample ?

**Comment by renolooijmans** [comment]
Thanks for your reply @dm77! No hurry, I was using a custom ZXingScannerView and figured out (way too late.. stupid me) that this was causing it.
`} catch(RuntimeException e) {
            // TODO: Terrible hack. It is possible that this method is invoked after camera is released.
            Log.e(TAG, e.toString(), e);
        }`

In my own version I forgot to catch the exception, and in your version it kept logging the exception, I had no idea this was causing it back then. It is solved for me, now.

Thanks :-)

**Comment by HendrikFW** [comment]
Could you please provide a more comlpete soulution? Im also facing this error all the time.

**Comment by Pbhaskarreddy** [comment]
Hi.Please provide a solution for this. I am using scanner fragment,

**Comment by tusharmehta02** [comment]
Hi, I am also getting the same exception:

2019-05-28 23:09:29.727 32351-627/com.tingcard E/ZXingScannerView: java.lang.RuntimeException: Camera is being used after Camera.release() was called
    java.lang.RuntimeException: Camera is being used after Camera.release() was called
        at android.hardware.Camera.setHasPreviewCallback(Native Method)
        at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:893)
        at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:169)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1204)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)


Please help.
