### ISSUE TITLE
Camera height and width is getting altered when returning from another activity with following error

### ISSUE THREAD

**Issue by hemapanjakshram** [dm77/barcodescanner#321]
java.lang.ArrayIndexOutOfBoundsException: length=1843200; index=1843559
                                                                                      at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(SourceFile:97)
                                                                                      at com.enstage.wibmo.wallet.mvisa.scanners.ZXingScannerView.onPreviewFrame(SourceFile:21)
                                                                                      at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1110)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by hemapanjakshram** [comment]
closed
