### ISSUE TITLE
Crashes on Samsung S phones

### ISSUE THREAD

**Issue by tartacutza** [dm77/barcodescanner#352]
` java.lang.RuntimeException: getParameters failed (empty parameters)
                                                                             at android.hardware.Camera.native_getParameters(Native Method)
                                                                             at android.hardware.Camera.getParameters(Camera.java:1952)
                                                                             at me.dm7.barcodescanner.core.CameraUtils.isFlashSupported(CameraUtils.java:47)
                                                                             at me.dm7.barcodescanner.core.BarcodeScannerView.setFlash(BarcodeScannerView.java:252)
                                                                             at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(BarcodeScannerView.java:189)
                                                                             at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java:31)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by dm77** [comment]
@tartacutza Do you have info on the exact phone model and Android OS version? Thank you

**Comment by tartacutza** [comment]
It happened on S6s, S7s both had Android 7.

**Comment by dm77** [comment]
ok thanks

**Comment by kkhash** [comment]
this problem is  fixed?

**Comment by dm77** [comment]
@kkhash I couldn't replicate the problem on Samsung Galaxy S6. Seems like it happens when you turn on flash, but I couldn't replicate yet. Will keep at it...

**Comment by tartacutza** [comment]
try turning the flash on from the start. That's how it crashed on my app

**Comment by dm77** [comment]
Thank you @tartacutza

**Comment by igormartsekha** [comment]
I have the same error on Xiomi Mi A1 and Android version 8.0.0

**Comment by igormartsekha** [comment]
I have this crash if I execute startCamera() twice on the same instance of ZXingScannerView

**Comment by ahmedeltaher** [comment]
I'm suffering from this crash a lot:/, is there no solution for it!

**Comment by yendangn** [comment]
I have the same issue, on S7, Android 7.
The log:

Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1952)
       at me.dm7.barcodescanner.core.CameraUtils.isFlashSupported(CameraUtils.java:47)
       at me.dm7.barcodescanner.core.BarcodeScannerView.setFlash(BarcodeScannerView.java:253)
       at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(BarcodeScannerView.java:190)
       at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java:31)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
