### ISSUE TITLE
App crash in start with compileSdk 27

### ISSUE THREAD

**Issue by Paul75** [dm77/barcodescanner#391]
Hello,

I've got a crash when update to minSdk 27 : 

`Device: Asus ASUS_Z012D 

Stack trace:  
java.lang.NoSuchFieldError: no "J" field "peer" in class "Lnet/sourceforge/zbar/ImageScanner;" or its superclasses
at net.sourceforge.zbar.ImageScanner.init(Native Method)
at net.sourceforge.zbar.ImageScanner.<clinit>(Unknown Source)
at me.a.a.b.c.d(Unknown Source)
at me.a.a.b.c.<init>(Unknown Source)
at fr.laposte.gompost.activity.scans.ScannerActivity.onCreate(Unknown Source)
at android.app.Activity.performCreate(Activity.java:6743)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:159)
at android.app.ActivityThread.main(ActivityThread.java:6097)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
`

Thanks

**Comment by Paul75** [comment]
Hello,

Solved by add into proguard this : 

`-keep class me.dm7.barcodescanner.** {
  *;
}

-keep class net.sourceforge.zbar.** {
  *;
}`

Thanks
