### ISSUE TITLE
zbar dont's work

### ISSUE THREAD

**Issue by sheng930920** [dm77/barcodescanner#407]
I reference zbar-sample to use, you can display ZBarScannerView, but the scanning interface is black can not identify the scan, how to deal with this situation change
![image](https://user-images.githubusercontent.com/13199067/35718217-7a3c27c6-081e-11e8-803e-5c9c729d1c7c.png)

**Comment by sheng930920** [comment]
E/CameraPreview: java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                           java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                               at android.hardware.Camera.native_cancelAutoFocus(Native Method)
                                                                               at android.hardware.Camera.cancelAutoFocus(Camera.java:1720)
                                                                               at me.dm7.barcodescanner.core.CameraPreview.stopCameraPreview(CameraPreview.java:120)
                                                                               at me.dm7.barcodescanner.core.CameraPreview.surfaceChanged(CameraPreview.java:72)
                                                                               at android.view.SurfaceView.updateWindow(SurfaceView.java:688)
                                                                               at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:202)
                                                                               at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2392)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1319)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6678)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:572)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                               at android.os.Handler.handleCallback(Handler.java:815)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                               at android.os.Looper.loop(Looper.java:194)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
02-02 13:41:40.738 26495-26495/com.gosstech.expressdriver E/CameraPreview: java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                           java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                               at android.hardware.Camera.native_getParameters(Native Method)
                                                                               at android.hardware.Camera.getParameters(Camera.java:3195)
                                                                               at me.dm7.barcodescanner.core.CameraPreview.getOptimalPreviewSize(CameraPreview.java:234)
                                                                               at me.dm7.barcodescanner.core.CameraPreview.setupCameraParameters(CameraPreview.java:130)
                                                                               at me.dm7.barcodescanner.core.CameraPreview.showCameraPreview(CameraPreview.java:87)
                                                                               at me.dm7.barcodescanner.core.CameraPreview.surfaceChanged(CameraPreview.java:73)
                                                                               at android.view.SurfaceView.updateWindow(SurfaceView.java:688)
                                                                               at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:202)
                                                                               at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2392)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1319)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6678)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:572)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                               at android.os.Handler.handleCallback(Handler.java:815)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                               at android.os.Looper.loop(Looper.java:194)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
