### ISSUE TITLE
sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by yhassanzadeh13** [dm77/barcodescanner#428]
Hello,

I am starting a ZXing barcode scanner activity from a broadcast receiver. The first time everything goes well, however, from the second time I am receiving the following exception. I have also double checked that I do not make a call to startCamera two times in the current activity. Also, I stop the camera as it said in the lifecycle callbacks.

`E/libc: Access denied finding property "camera.hal1.packagelist"
W/MessageQueue: Handler (android.hardware.Camera$EventHandler) {18e7467} sending message to a Handler on a dead thread
                java.lang.IllegalStateException: Handler (android.hardware.Camera$EventHandler) {18e7467} sending message to a Handler on a dead thread
                    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:638)
                    at android.os.Handler.enqueueMessage(Handler.java:661)
                    at android.os.Handler.sendMessageAtTime(Handler.java:630)
                    at android.os.Handler.sendMessageDelayed(Handler.java:600)
                    at android.os.Handler.sendMessage(Handler.java:537)
                    at android.hardware.Camera.postEventFromNative(Camera.java:1284)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.stackparse.barcodescanner, PID: 26729
                  java.lang.RuntimeException: getParameters failed (empty parameters)
                      at android.hardware.Camera.native_getParameters(Native Method)
                      at android.hardware.Camera.getParameters(Camera.java:2027)
                      at me.dm7.barcodescanner.core.CameraUtils.isFlashSupported(CameraUtils.java:47)
                      at me.dm7.barcodescanner.core.BarcodeScannerView.setFlash(BarcodeScannerView.java:253)
                      at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(BarcodeScannerView.java:190)
                      at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java:31)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:251)
                      at android.app.ActivityThread.main(ActivityThread.java:6589)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

`    @Override
    public void onDestroy()
    {
         mScannerView.stopCameraPreview(); //stopPreview
         mScannerView.stopCamera();
         mScannerView.destroyDrawingCache();      
        super.onDestroy();
    }

 @Override
    public void onPause()
    {
        super.onPause();
         mScannerView.stopCamera();
    }

`

**Comment by n002213f** [comment]
Any luck with the issue, i'm also getting the same issue on Android 8.0

**Comment by paulsenjs** [comment]
somebody can help about this issue ?

**Comment by yhassanzadeh13** [comment]
@paulsenjs @n002213f I solve this problem by carefully logging all the life cycle functions of my app which are correlated with the scanner e.g., onPause. I then realize that the scanner somehow magically invokes some event handler twice. I may not remember it exactly, but in my case, I think the onResume function was getting called twice and there was nothing I could do to make it getting called once. The problem was that I was opening my scanner camera in onResume, and (although I would expect this function to get called only once) with it twice getting called it was rising the exception. As the solution then, I added a Semaphor using an integer, which does not allow the camera to get opened on the second call. Hope it fixes your problems.

**Comment by raveesh08** [comment]
Hi Guys,
i think found the temporary solution to this error, i don't know whether it's the correct way of doing it  or not as i'm not aware of the internal code.

Just use 

```
startCamera function in onCreate
stopCamera  function in onDestroy

resumeCameraPreview function in onResume
stopCameraPreview   function in onPause
```

it will stop that error.

**Comment by raveesh08** [comment]
> Any luck with the issue, i'm also getting the same issue on Android 8.0

check my solution

**Comment by raveesh08** [comment]
> somebody can help about this issue ?

check my solution
