### ISSUE TITLE
 Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by btcw** [dm77/barcodescanner#439]
I've solved it with adding "scannerView.stopCameraPreview()" before "scannerView.stopCamera()" in onPase(),like this:

    public override fun onPause() {
        super.onPause()
        scannerView.stopCameraPreview()
        scannerView.stopCamera()     
    }

**Comment by diegogutierc** [comment]
I am having this issue as well, using Fragment. Fix from btcw did not work for me

**Comment by dsdebastiani** [comment]
I have the same problem using Activity. Fix from @btcw doesn’t work for me.


Android: 9
Barcodescanner version: 1.9.13

Steps to reproduce.

1. After you open the scanner view, press home button.
1. Return to app from android app history.
1. Press home button again.

Stack-trace:
```
E/ZXingScannerView: java.lang.RuntimeException: Camera is being used after Camera.release() was called
    java.lang.RuntimeException: Camera is being used after Camera.release() was called
        at android.hardware.Camera.setHasPreviewCallback(Native Method)
        at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:977)
        at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:169)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1289)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
