### ISSUE TITLE
java.lang.NullPointerException at ZXingScannerView.onPreviewFrame

### ISSUE THREAD

**Issue by MrEngineer13** [dm77/barcodescanner#47]
I am using v1.6 of your library and on certain devices specifically the PantechP9070 and ZTE V768 I am getting a `NullPointerException` which happens at [ZXingScannerView.java:90](https://github.com/dm77/barcodescanner/blob/master/zxing/zxing/src/main/java/me/dm7/barcodescanner/zxing/ZXingScannerView.java#L90). It seems like there is an issue with creating the camera preview, how can I solve this?

```
java.lang.NullPointerException
       at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:90)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:603)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:3818)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by dm77** [comment]
Sorry for never replying to this issue. Given that it has been open over 2 years without any further activity I am going to close this issue.
