### ISSUE TITLE
Crash in api < 24

### ISSUE THREAD

**Issue by juandallaglio** [dm77/barcodescanner#508]
Hi, 

i have this crash when read a qr code with a camera, is the same code that example FullScannerActivity.java

`AndroidRuntime: FATAL EXCEPTION: CameraHandlerThread
   
    java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
        at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
        at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:125)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1183)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
`

I read over the problem, and this is because the lib zxing:core use Java 8 and this is not support in api < 24. The solution is compiler zxing:core version 3.3.3.

It's possible?

or exist other implementation?

Thank you.

**Comment by juandallaglio** [comment]
or which version of this lib use zxing:core 3.3.3?

**Comment by jnischler** [comment]
Hey
this is caused by this issue https://github.com/zxing/zxing/issues/1170

should downgrade zxing:core to version 3.3.X
Problem starts with version 3.4.0+

regards
