### ISSUE TITLE
Cancel Button throws Java Exception

### ISSUE THREAD

**Issue by DaDummy** [dm77/barcodescanner#536]
The following Exception is logged when tapping the "Cancel"-Button on Android with barcode_scanner version 3.0.1:
```
E/ZXingScannerView(10883): java.lang.RuntimeException: Camera is being used after Camera.release() was called
E/ZXingScannerView(10883): java.lang.RuntimeException: Camera is being used after Camera.release() was called
E/ZXingScannerView(10883): 	at android.hardware.Camera.native_getParameters(Native Method)
E/ZXingScannerView(10883): 	at android.hardware.Camera.getParameters(Camera.java:1910)
E/ZXingScannerView(10883): 	at me.dm7.barcodescanner.core.BarcodeScannerView.getRotatedData(BarcodeScannerView.java:309)
E/ZXingScannerView(10883): 	at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:116)
E/ZXingScannerView(10883): 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1124)
E/ZXingScannerView(10883): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/ZXingScannerView(10883): 	at android.os.Looper.loop(Looper.java:164)
E/ZXingScannerView(10883): 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by DaDummy** [comment]
Uh sorry wrong project.
