### ISSUE TITLE
64bit device crash

### ISSUE THREAD

**Issue by yangkong** [dm77/barcodescanner#94]
Samsung GALAXY S6 device

log 

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/my.package.name-2/base.apk"],nativeLibraryDirectories=[/data/app/my.package.name-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libiconv.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:366)
	at java.lang.System.loadLibrary(System.java:989)
	at me.dm7.barcodescanner.zbar.ZBarScannerView.<clinit>(ZBarScannerView.java:31)
	at my.package.name.activity.BarcodeActivity.onCreate(BarcodeActivity.java:19)
	at android.app.Activity.performCreate(Activity.java:6374)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2767)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2879)
	at android.app.ActivityThread.access$900(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6141)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by tigerdog** [comment]
find it in zbar\src\main\jniLibs\armeabi  .

**Comment by dm77** [comment]
Hi @yangkong I am guessing this is due to the inavailability of the iconv.so library for arm64 and S6 being a 64-bit device?

I added more platform specific libraries in v1.8.3 (https://github.com/dm77/barcodescanner/tree/master/zbar/zbar/src/main/jniLibs). Please let me know if this solved your issue.

**Comment by larsdecker** [comment]
The problem still exists with a nexus 5x.
java.lang.UnsatisfiedLinkError. couldn't find "libiconv.so"

**Comment by PratikPagada** [comment]
The problem still exists with a nexus 6p os version 7.1.1.

java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.logistic.anikavisco-1/lib/arm/libmupdf.so: has text relocations
